message(STATUS "Running cleanup script with prefix [/usr/local]")
file(GLOB OLD_LIB_FILES /usr/lib/*ta_lib* /usr/local/lib/*ta_lib*)
foreach(file ${OLD_LIB_FILES})
    file(REMOVE ${file})
endforeach()
foreach(header ta_abstract.h;ta_accel.h;ta_accel_plan.h;ta_common.h;ta_defs.h;ta_func.h;ta_libc.h)
    file(REMOVE /usr/local/include/${header} /usr/include/${header})
endforeach()
if("/usr/local" STREQUAL "/usr")
    file(REMOVE_RECURSE /usr/local/include/ta-lib)
    file(GLOB OLD_LIB_FILES /usr/local/lib/*ta-lib*)
    foreach(file ${OLD_LIB_FILES})
        file(REMOVE ${file})
    endforeach()
elseif("/usr/local" STREQUAL "/usr/local")
    file(REMOVE_RECURSE /usr/include/ta-lib)
    file(GLOB OLD_LIB_FILES /usr/lib/*ta-lib*)
    foreach(file ${OLD_LIB_FILES})
        file(REMOVE ${file})
    endforeach()
endif()
