/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* List of contributors:
 *
 *  Initial  Name/description
 *  -------------------------------------------------------------------
 *  MF       Mario Fortier
 *  SS       Sean Skender (port of Williams Alligator)
 *
 * Change history:
 *
 *  MMDDYY BY   Description
 *  -------------------------------------------------------------------
 *  011325 SS   Initial public implementation.
 */

/**** START GENCODE SECTION 1 - DO NOT DELETE THIS LINE ****/
/* All code within this section is automatically
 * generated by gen_code. Any modification will be lost
 * next time gen_code is run.
 */
/* Generated */ 
/* Generated */ #if defined( _MANAGED )
/* Generated */    #include "TA-Lib-Core.h"
/* Generated */    #define TA_INTERNAL_ERROR(Id) (RetCode::InternalError)
/* Generated */    namespace TicTacTec { namespace TA { namespace Library {
/* Generated */ #elif defined( _JAVA )
/* Generated */    #include "ta_defs.h"
/* Generated */    #include "ta_java_defs.h"
/* Generated */    #define TA_INTERNAL_ERROR(Id) (RetCode.InternalError)
/* Generated */ #elif defined( _RUST )
/* Generated */    #include "ta_defs.h"
/* Generated */    #define TA_INTERNAL_ERROR(Id) (RetCode.InternalError)
/* Generated */    impl core {
/* Generated */ #else
/* Generated */    #include <string.h>
/* Generated */    #include <math.h>
/* Generated */    #include "ta_func.h"
/* Generated */ #endif
/* Generated */ 
/* Generated */ #ifndef TA_UTILITY_H
/* Generated */    #include "ta_utility.h"
/* Generated */ #endif
/* Generated */ 
/* Generated */ #ifndef TA_MEMORY_H
/* Generated */    #include "ta_memory.h"
/* Generated */ #endif
/* Generated */ 
/* Generated */ #define TA_PREFIX(x) TA_##x
/* Generated */ #define INPUT_TYPE   double
/* Generated */ 
/* Generated */ #if defined( _MANAGED )
/* Generated */ int Core::AlligatorLookback( int           optInJawPeriod, /* From 1 to 100000 */
/* Generated */                            int           optInJawOffset, /* From 1 to 100000 */
/* Generated */                            int           optInTeethPeriod, /* From 1 to 100000 */
/* Generated */                            int           optInTeethOffset, /* From 1 to 100000 */
/* Generated */                            int           optInLipsPeriod, /* From 1 to 100000 */
/* Generated */                            int           optInLipsOffset )  /* From 1 to 100000 */
/* Generated */ 
/* Generated */ #elif defined( _JAVA )
/* Generated */ public int alligatorLookback( int           optInJawPeriod, /* From 1 to 100000 */
/* Generated */                             int           optInJawOffset, /* From 1 to 100000 */
/* Generated */                             int           optInTeethPeriod, /* From 1 to 100000 */
/* Generated */                             int           optInTeethOffset, /* From 1 to 100000 */
/* Generated */                             int           optInLipsPeriod, /* From 1 to 100000 */
/* Generated */                             int           optInLipsOffset )  /* From 1 to 100000 */
/* Generated */ 
/* Generated */ #elif defined( _RUST )
/* Generated */ fn alligator_lookback( /* Generated */ 
/* Generated */ #else
/* Generated */ TA_LIB_API int TA_ALLIGATOR_Lookback( int           optInJawPeriod, /* From 1 to 100000 */
/* Generated */                                                int           optInJawOffset, /* From 1 to 100000 */
/* Generated */                                                int           optInTeethPeriod, /* From 1 to 100000 */
/* Generated */                                                int           optInTeethOffset, /* From 1 to 100000 */
/* Generated */                                                int           optInLipsPeriod, /* From 1 to 100000 */
/* Generated */                                                int           optInLipsOffset )  /* From 1 to 100000 */
/* Generated */ 
/* Generated */ #endif
/**** END GENCODE SECTION 1 - DO NOT DELETE THIS LINE ****/
{
   /* insert local variable here */
   int jawSpan, teethSpan, lipsSpan;

/**** START GENCODE SECTION 2 - DO NOT DELETE THIS LINE ****/
/* Generated */ #ifndef TA_FUNC_NO_RANGE_CHECK
/* Generated */    /* min/max are checked for optInJawPeriod. */
/* Generated */    if( (int)optInJawPeriod == TA_INTEGER_DEFAULT )
/* Generated */       optInJawPeriod = 13;
/* Generated */    else if( ((int)optInJawPeriod < 1) || ((int)optInJawPeriod > 100000) )
/* Generated */       return -1;
/* Generated */ 
/* Generated */    /* min/max are checked for optInJawOffset. */
/* Generated */    if( (int)optInJawOffset == TA_INTEGER_DEFAULT )
/* Generated */       optInJawOffset = 8;
/* Generated */    else if( ((int)optInJawOffset < 1) || ((int)optInJawOffset > 100000) )
/* Generated */       return -1;
/* Generated */ 
/* Generated */    /* min/max are checked for optInTeethPeriod. */
/* Generated */    if( (int)optInTeethPeriod == TA_INTEGER_DEFAULT )
/* Generated */       optInTeethPeriod = 8;
/* Generated */    else if( ((int)optInTeethPeriod < 1) || ((int)optInTeethPeriod > 100000) )
/* Generated */       return -1;
/* Generated */ 
/* Generated */    /* min/max are checked for optInTeethOffset. */
/* Generated */    if( (int)optInTeethOffset == TA_INTEGER_DEFAULT )
/* Generated */       optInTeethOffset = 5;
/* Generated */    else if( ((int)optInTeethOffset < 1) || ((int)optInTeethOffset > 100000) )
/* Generated */       return -1;
/* Generated */ 
/* Generated */    /* min/max are checked for optInLipsPeriod. */
/* Generated */    if( (int)optInLipsPeriod == TA_INTEGER_DEFAULT )
/* Generated */       optInLipsPeriod = 5;
/* Generated */    else if( ((int)optInLipsPeriod < 1) || ((int)optInLipsPeriod > 100000) )
/* Generated */       return -1;
/* Generated */ 
/* Generated */    /* min/max are checked for optInLipsOffset. */
/* Generated */    if( (int)optInLipsOffset == TA_INTEGER_DEFAULT )
/* Generated */       optInLipsOffset = 3;
/* Generated */    else if( ((int)optInLipsOffset < 1) || ((int)optInLipsOffset > 100000) )
/* Generated */       return -1;
/* Generated */ 
/* Generated */ #endif /* TA_FUNC_NO_RANGE_CHECK */
/**** END GENCODE SECTION 2 - DO NOT DELETE THIS LINE ****/

   /* insert lookback code here. */
   jawSpan   = optInJawPeriod   + optInJawOffset   - 1;
   teethSpan = optInTeethPeriod + optInTeethOffset - 1;
   lipsSpan  = optInLipsPeriod  + optInLipsOffset  - 1;

   if( teethSpan > jawSpan )
      jawSpan = teethSpan;
   if( lipsSpan > jawSpan )
      jawSpan = lipsSpan;

   return jawSpan;
}

/**** START GENCODE SECTION 3 - DO NOT DELETE THIS LINE ****/
/*
 * TA_ALLIGATOR - Williams Alligator
 * 
 * Input  = High, Low
 * Output = double, double, double
 * 
 * Optional Parameters
 * -------------------
 * optInJawPeriod:(From 1 to 100000)
 *    Number of periods for the jaw smoothing
 * 
 * optInJawOffset:(From 1 to 100000)
 *    Forward offset applied to the jaw line
 * 
 * optInTeethPeriod:(From 1 to 100000)
 *    Number of periods for the teeth smoothing
 * 
 * optInTeethOffset:(From 1 to 100000)
 *    Forward offset applied to the teeth line
 * 
 * optInLipsPeriod:(From 1 to 100000)
 *    Number of periods for the lips smoothing
 * 
 * optInLipsOffset:(From 1 to 100000)
 *    Forward offset applied to the lips line
 * 
 * 
 */
/* Generated */ 
/* Generated */ #if defined( _MANAGED ) && defined( USE_SUBARRAY )
/* Generated */ enum class Core::RetCode Core::Alligator( int    startIdx,
/* Generated */                                           int    endIdx,
/* Generated */                                           SubArray<double>^ inHigh,
/* Generated */                                           SubArray<double>^ inLow,
/* Generated */                                           int           optInJawPeriod, /* From 1 to 100000 */
/* Generated */                                           int           optInJawOffset, /* From 1 to 100000 */
/* Generated */                                           int           optInTeethPeriod, /* From 1 to 100000 */
/* Generated */                                           int           optInTeethOffset, /* From 1 to 100000 */
/* Generated */                                           int           optInLipsPeriod, /* From 1 to 100000 */
/* Generated */                                           int           optInLipsOffset, /* From 1 to 100000 */
/* Generated */                                           [Out]int%    outBegIdx,
/* Generated */                                           [Out]int%    outNBElement,
/* Generated */                                           SubArray<double>^  outJaw,
/* Generated */                                           SubArray<double>^  outTeeth,
/* Generated */                                           SubArray<double>^  outLips )
/* Generated */ #elif defined( _MANAGED )
/* Generated */ enum class Core::RetCode Core::Alligator( int    startIdx,
/* Generated */                                           int    endIdx,
/* Generated */                                           cli::array<double>^ inHigh,
/* Generated */                                           cli::array<double>^ inLow,
/* Generated */                                           int           optInJawPeriod, /* From 1 to 100000 */
/* Generated */                                           int           optInJawOffset, /* From 1 to 100000 */
/* Generated */                                           int           optInTeethPeriod, /* From 1 to 100000 */
/* Generated */                                           int           optInTeethOffset, /* From 1 to 100000 */
/* Generated */                                           int           optInLipsPeriod, /* From 1 to 100000 */
/* Generated */                                           int           optInLipsOffset, /* From 1 to 100000 */
/* Generated */                                           [Out]int%    outBegIdx,
/* Generated */                                           [Out]int%    outNBElement,
/* Generated */                                           cli::array<double>^  outJaw,
/* Generated */                                           cli::array<double>^  outTeeth,
/* Generated */                                           cli::array<double>^  outLips )
/* Generated */ #elif defined( _JAVA )
/* Generated */ public RetCode alligator( int    startIdx,
/* Generated */                           int    endIdx,
/* Generated */                           double       inHigh[],
/* Generated */                           double       inLow[],
/* Generated */                           int           optInJawPeriod, /* From 1 to 100000 */
/* Generated */                           int           optInJawOffset, /* From 1 to 100000 */
/* Generated */                           int           optInTeethPeriod, /* From 1 to 100000 */
/* Generated */                           int           optInTeethOffset, /* From 1 to 100000 */
/* Generated */                           int           optInLipsPeriod, /* From 1 to 100000 */
/* Generated */                           int           optInLipsOffset, /* From 1 to 100000 */
/* Generated */                           MInteger     outBegIdx,
/* Generated */                           MInteger     outNBElement,
/* Generated */                           double        outJaw[],
/* Generated */                           double        outTeeth[],
/* Generated */                           double        outLips[] )
/* Generated */ #elif defined( _RUST )
/* Generated */ fn alligator( int    startIdx,
/* Generated */ 
/* Generated */                                int    endIdx,
double inPriceHL[],
int optInJawPeriod[],
int optInJawOffset[],
int optInTeethPeriod[],
int optInTeethOffset[],
int optInLipsPeriod[],
int optInLipsOffset[],
mut outBegIdx,
mut outNBElement,
double outJaw[],
double outTeeth[],
double outLips[],
)
/* Generated */ #else
/* Generated */ TA_LIB_API TA_RetCode TA_ALLIGATOR( int    startIdx,
/* Generated */                                     int    endIdx,
/* Generated */                                                const double inHigh[],
/* Generated */                                                const double inLow[],
/* Generated */                                                int           optInJawPeriod, /* From 1 to 100000 */
/* Generated */                                                int           optInJawOffset, /* From 1 to 100000 */
/* Generated */                                                int           optInTeethPeriod, /* From 1 to 100000 */
/* Generated */                                                int           optInTeethOffset, /* From 1 to 100000 */
/* Generated */                                                int           optInLipsPeriod, /* From 1 to 100000 */
/* Generated */                                                int           optInLipsOffset, /* From 1 to 100000 */
/* Generated */                                                int          *outBegIdx,
/* Generated */                                                int          *outNBElement,
/* Generated */                                                double        outJaw[],
/* Generated */                                                double        outTeeth[],
/* Generated */                                                double        outLips[] )
/* Generated */ #endif
/**** END GENCODE SECTION 3 - DO NOT DELETE THIS LINE ****/
{
   /* insert local variable here */
   int jawSpan, teethSpan, lipsSpan;
   int lookbackTotal, firstCalcIdx;
   int today, outIdx;
   double jawPrev = 0.0, teethPrev = 0.0, lipsPrev = 0.0;
   int jawInitialized = 0, teethInitialized = 0, lipsInitialized = 0;

/**** START GENCODE SECTION 4 - DO NOT DELETE THIS LINE ****/
/* Generated */ 
/* Generated */ #ifndef TA_FUNC_NO_RANGE_CHECK
/* Generated */ 
/* Generated */    /* Validate the requested output range. */
/* Generated */    if( startIdx < 0 )
/* Generated */       return ENUM_VALUE(RetCode,TA_OUT_OF_RANGE_START_INDEX,OutOfRangeStartIndex);
/* Generated */    if( (endIdx < 0) || (endIdx < startIdx))
/* Generated */       return ENUM_VALUE(RetCode,TA_OUT_OF_RANGE_END_INDEX,OutOfRangeEndIndex);
/* Generated */ 
/* Generated */ #if defined( _RUST )
/* Generated */ 
/* Generated */ #else
/* Generated */    #if !defined(_JAVA)
/* Generated */    /* Verify required price component. */
/* Generated */    if(!inHigh||!inLow)
/* Generated */       return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */ 
/* Generated */    #endif /* !defined(_JAVA)*/
/* Generated */    /* min/max are checked for optInJawPeriod. */
/* Generated */    if( (int)optInJawPeriod == TA_INTEGER_DEFAULT )
/* Generated */       optInJawPeriod = 13;
/* Generated */    else if( ((int)optInJawPeriod < 1) || ((int)optInJawPeriod > 100000) )
/* Generated */       return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */ 
/* Generated */    /* min/max are checked for optInJawOffset. */
/* Generated */    if( (int)optInJawOffset == TA_INTEGER_DEFAULT )
/* Generated */       optInJawOffset = 8;
/* Generated */    else if( ((int)optInJawOffset < 1) || ((int)optInJawOffset > 100000) )
/* Generated */       return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */ 
/* Generated */    /* min/max are checked for optInTeethPeriod. */
/* Generated */    if( (int)optInTeethPeriod == TA_INTEGER_DEFAULT )
/* Generated */       optInTeethPeriod = 8;
/* Generated */    else if( ((int)optInTeethPeriod < 1) || ((int)optInTeethPeriod > 100000) )
/* Generated */       return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */ 
/* Generated */    /* min/max are checked for optInTeethOffset. */
/* Generated */    if( (int)optInTeethOffset == TA_INTEGER_DEFAULT )
/* Generated */       optInTeethOffset = 5;
/* Generated */    else if( ((int)optInTeethOffset < 1) || ((int)optInTeethOffset > 100000) )
/* Generated */       return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */ 
/* Generated */    /* min/max are checked for optInLipsPeriod. */
/* Generated */    if( (int)optInLipsPeriod == TA_INTEGER_DEFAULT )
/* Generated */       optInLipsPeriod = 5;
/* Generated */    else if( ((int)optInLipsPeriod < 1) || ((int)optInLipsPeriod > 100000) )
/* Generated */       return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */ 
/* Generated */    /* min/max are checked for optInLipsOffset. */
/* Generated */    if( (int)optInLipsOffset == TA_INTEGER_DEFAULT )
/* Generated */       optInLipsOffset = 3;
/* Generated */    else if( ((int)optInLipsOffset < 1) || ((int)optInLipsOffset > 100000) )
/* Generated */       return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */ 
/* Generated */    #if !defined(_JAVA)
/* Generated */    if( !outJaw )
/* Generated */       return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */ 
/* Generated */    if( !outTeeth )
/* Generated */       return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */ 
/* Generated */    if( !outLips )
/* Generated */       return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */ 
/* Generated */    #endif /* !defined(_JAVA) */
/* Generated */ #endif
/* Generated */ #endif /* TA_FUNC_NO_RANGE_CHECK */
/* Generated */ 
/**** END GENCODE SECTION 4 - DO NOT DELETE THIS LINE ****/

   jawSpan   = optInJawPeriod   + optInJawOffset   - 1;
   teethSpan = optInTeethPeriod + optInTeethOffset - 1;
   lipsSpan  = optInLipsPeriod  + optInLipsOffset  - 1;

   lookbackTotal = jawSpan;
   if( teethSpan > lookbackTotal )
      lookbackTotal = teethSpan;
   if( lipsSpan > lookbackTotal )
      lookbackTotal = lipsSpan;

   firstCalcIdx = jawSpan;
   if( teethSpan < firstCalcIdx )
      firstCalcIdx = teethSpan;
   if( lipsSpan < firstCalcIdx )
      firstCalcIdx = lipsSpan;

   if( startIdx < lookbackTotal )
      startIdx = lookbackTotal;

   if( startIdx > endIdx )
   {
      VALUE_HANDLE_DEREF_TO_ZERO(outBegIdx);
      VALUE_HANDLE_DEREF_TO_ZERO(outNBElement);
      return ENUM_VALUE(RetCode,TA_SUCCESS,Success);
   }

   /* Warm up calculations so the smoothing state is ready when outputs begin */
   if( firstCalcIdx < startIdx )
   {
      for( today = firstCalcIdx; today < startIdx; ++today )
      {
         double tmpJaw   = TA_REAL_DEFAULT;
         double tmpTeeth = TA_REAL_DEFAULT;
         double tmpLips  = TA_REAL_DEFAULT;
#define CALC_LINE(periodVar, offsetVar, startVar, initVar, prevVar, valueVar) \
         do { \
            if( today >= (startVar) ) \
            { \
               if( !(initVar) ) \
               { \
                  double sum_ = 0.0; \
                  int idx_; \
                  int begin_ = today - (offsetVar) - (periodVar) + 1; \
                  int end_ = today - (offsetVar); \
                  for( idx_ = begin_; idx_ <= end_; ++idx_ ) \
                     sum_ += (((double)inHigh[idx_]) + ((double)inLow[idx_])) * 0.5; \
                  valueVar = sum_ / (double)(periodVar); \
                  initVar = 1; \
               } \
               else \
               { \
                  double input_ = (((double)inHigh[today - (offsetVar)]) + ((double)inLow[today - (offsetVar)])) * 0.5; \
                  valueVar = ((prevVar * ((double)(periodVar) - 1.0)) + input_) / (double)(periodVar); \
               } \
               prevVar = valueVar; \
            } \
         } while(0)

         CALC_LINE(optInJawPeriod, optInJawOffset, jawSpan, jawInitialized, jawPrev, tmpJaw);
         CALC_LINE(optInTeethPeriod, optInTeethOffset, teethSpan, teethInitialized, teethPrev, tmpTeeth);
         CALC_LINE(optInLipsPeriod, optInLipsOffset, lipsSpan, lipsInitialized, lipsPrev, tmpLips);
#undef CALC_LINE
      }
   }

   outIdx = 0;
   for( today = startIdx; today <= endIdx; ++today )
   {
   double jawValue   = TA_REAL_DEFAULT;
   double teethValue = TA_REAL_DEFAULT;
   double lipsValue  = TA_REAL_DEFAULT;
#define CALC_LINE(periodVar, offsetVar, startVar, initVar, prevVar, valueVar) \
      do { \
         if( today >= (startVar) ) \
         { \
            if( !(initVar) ) \
            { \
               double sum_ = 0.0; \
               int idx_; \
               int begin_ = today - (offsetVar) - (periodVar) + 1; \
               int end_ = today - (offsetVar); \
               for( idx_ = begin_; idx_ <= end_; ++idx_ ) \
                  sum_ += (((double)inHigh[idx_]) + ((double)inLow[idx_])) * 0.5; \
               valueVar = sum_ / (double)(periodVar); \
               initVar = 1; \
            } \
            else \
            { \
               double input_ = (((double)inHigh[today - (offsetVar)]) + ((double)inLow[today - (offsetVar)])) * 0.5; \
               valueVar = ((prevVar * ((double)(periodVar) - 1.0)) + input_) / (double)(periodVar); \
            } \
            prevVar = valueVar; \
         } \
         else \
         { \
            valueVar = TA_REAL_DEFAULT; \
         } \
      } while(0)

      CALC_LINE(optInJawPeriod, optInJawOffset, jawSpan, jawInitialized, jawPrev, jawValue);
      CALC_LINE(optInTeethPeriod, optInTeethOffset, teethSpan, teethInitialized, teethPrev, teethValue);
      CALC_LINE(optInLipsPeriod, optInLipsOffset, lipsSpan, lipsInitialized, lipsPrev, lipsValue);
#undef CALC_LINE

      outJaw[outIdx]   = jawValue;
      outTeeth[outIdx] = teethValue;
      outLips[outIdx]  = lipsValue;
      outIdx++;
   }

   VALUE_HANDLE_DEREF(outBegIdx)    = startIdx;
   VALUE_HANDLE_DEREF(outNBElement) = outIdx;

   return ENUM_VALUE(RetCode,TA_SUCCESS,Success);
}

/**** START GENCODE SECTION 5 - DO NOT DELETE THIS LINE ****/
/* Generated */ 
/* Generated */ #define  USE_SINGLE_PRECISION_INPUT
/* Generated */ #if !defined( _MANAGED ) && !defined( _JAVA )
/* Generated */    #undef   TA_PREFIX
/* Generated */    #define  TA_PREFIX(x) TA_S_##x
/* Generated */ #endif
/* Generated */ #undef   INPUT_TYPE
/* Generated */ #define  INPUT_TYPE float
/* Generated */ #if defined( _MANAGED ) && defined( USE_SUBARRAY )
/* Generated */ enum class Core::RetCode Core::Alligator( int    startIdx,
/* Generated */                                           int    endIdx,
/* Generated */                                           SubArray<float>^ inHigh,
/* Generated */                                           SubArray<float>^ inLow,
/* Generated */                                           int           optInJawPeriod, /* From 1 to 100000 */
/* Generated */                                           int           optInJawOffset, /* From 1 to 100000 */
/* Generated */                                           int           optInTeethPeriod, /* From 1 to 100000 */
/* Generated */                                           int           optInTeethOffset, /* From 1 to 100000 */
/* Generated */                                           int           optInLipsPeriod, /* From 1 to 100000 */
/* Generated */                                           int           optInLipsOffset, /* From 1 to 100000 */
/* Generated */                                           [Out]int%    outBegIdx,
/* Generated */                                           [Out]int%    outNBElement,
/* Generated */                                           SubArray<double>^  outJaw,
/* Generated */                                           SubArray<double>^  outTeeth,
/* Generated */                                           SubArray<double>^  outLips )
/* Generated */ #elif defined( _MANAGED )
/* Generated */ enum class Core::RetCode Core::Alligator( int    startIdx,
/* Generated */                                           int    endIdx,
/* Generated */                                           cli::array<float>^ inHigh,
/* Generated */                                           cli::array<float>^ inLow,
/* Generated */                                           int           optInJawPeriod, /* From 1 to 100000 */
/* Generated */                                           int           optInJawOffset, /* From 1 to 100000 */
/* Generated */                                           int           optInTeethPeriod, /* From 1 to 100000 */
/* Generated */                                           int           optInTeethOffset, /* From 1 to 100000 */
/* Generated */                                           int           optInLipsPeriod, /* From 1 to 100000 */
/* Generated */                                           int           optInLipsOffset, /* From 1 to 100000 */
/* Generated */                                           [Out]int%    outBegIdx,
/* Generated */                                           [Out]int%    outNBElement,
/* Generated */                                           cli::array<double>^  outJaw,
/* Generated */                                           cli::array<double>^  outTeeth,
/* Generated */                                           cli::array<double>^  outLips )
/* Generated */ #elif defined( _JAVA )
/* Generated */ public RetCode alligator( int    startIdx,
/* Generated */                           int    endIdx,
/* Generated */                           float        inHigh[],
/* Generated */                           float        inLow[],
/* Generated */                           int           optInJawPeriod, /* From 1 to 100000 */
/* Generated */                           int           optInJawOffset, /* From 1 to 100000 */
/* Generated */                           int           optInTeethPeriod, /* From 1 to 100000 */
/* Generated */                           int           optInTeethOffset, /* From 1 to 100000 */
/* Generated */                           int           optInLipsPeriod, /* From 1 to 100000 */
/* Generated */                           int           optInLipsOffset, /* From 1 to 100000 */
/* Generated */                           MInteger     outBegIdx,
/* Generated */                           MInteger     outNBElement,
/* Generated */                           double        outJaw[],
/* Generated */                           double        outTeeth[],
/* Generated */                           double        outLips[] )
/* Generated */ #elif defined( _RUST )
/* Generated */ fn alligator_s( int    startIdx,
/* Generated */ 
/* Generated */                                  int    endIdx,
/* Generated */ #else
/* Generated */ TA_RetCode TA_S_ALLIGATOR( int    startIdx,
/* Generated */                            int    endIdx,
/* Generated */                            const float  inHigh[],
/* Generated */                            const float  inLow[],
/* Generated */                            int           optInJawPeriod, /* From 1 to 100000 */
/* Generated */                            int           optInJawOffset, /* From 1 to 100000 */
/* Generated */                            int           optInTeethPeriod, /* From 1 to 100000 */
/* Generated */                            int           optInTeethOffset, /* From 1 to 100000 */
/* Generated */                            int           optInLipsPeriod, /* From 1 to 100000 */
/* Generated */                            int           optInLipsOffset, /* From 1 to 100000 */
/* Generated */                            int          *outBegIdx,
/* Generated */                            int          *outNBElement,
/* Generated */                            double        outJaw[],
/* Generated */                            double        outTeeth[],
/* Generated */                            double        outLips[] )
/* Generated */ #endif
/* Generated */ {
/* Generated */    int jawSpan, teethSpan, lipsSpan;
/* Generated */    int lookbackTotal, firstCalcIdx;
/* Generated */    int today, outIdx;
/* Generated */    double jawPrev = 0.0, teethPrev = 0.0, lipsPrev = 0.0;
/* Generated */    int jawInitialized = 0, teethInitialized = 0, lipsInitialized = 0;
/* Generated */  #ifndef TA_FUNC_NO_RANGE_CHECK
/* Generated */     if( startIdx < 0 )
/* Generated */        return ENUM_VALUE(RetCode,TA_OUT_OF_RANGE_START_INDEX,OutOfRangeStartIndex);
/* Generated */     if( (endIdx < 0) || (endIdx < startIdx))
/* Generated */        return ENUM_VALUE(RetCode,TA_OUT_OF_RANGE_END_INDEX,OutOfRangeEndIndex);
/* Generated */  #if defined( _RUST )
/* Generated */  #else
/* Generated */     #if !defined(_JAVA)
/* Generated */     if(!inHigh||!inLow)
/* Generated */        return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */     #endif
/* Generated */     if( (int)optInJawPeriod == TA_INTEGER_DEFAULT )
/* Generated */        optInJawPeriod = 13;
/* Generated */     else if( ((int)optInJawPeriod < 1) || ((int)optInJawPeriod > 100000) )
/* Generated */        return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */     if( (int)optInJawOffset == TA_INTEGER_DEFAULT )
/* Generated */        optInJawOffset = 8;
/* Generated */     else if( ((int)optInJawOffset < 1) || ((int)optInJawOffset > 100000) )
/* Generated */        return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */     if( (int)optInTeethPeriod == TA_INTEGER_DEFAULT )
/* Generated */        optInTeethPeriod = 8;
/* Generated */     else if( ((int)optInTeethPeriod < 1) || ((int)optInTeethPeriod > 100000) )
/* Generated */        return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */     if( (int)optInTeethOffset == TA_INTEGER_DEFAULT )
/* Generated */        optInTeethOffset = 5;
/* Generated */     else if( ((int)optInTeethOffset < 1) || ((int)optInTeethOffset > 100000) )
/* Generated */        return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */     if( (int)optInLipsPeriod == TA_INTEGER_DEFAULT )
/* Generated */        optInLipsPeriod = 5;
/* Generated */     else if( ((int)optInLipsPeriod < 1) || ((int)optInLipsPeriod > 100000) )
/* Generated */        return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */     if( (int)optInLipsOffset == TA_INTEGER_DEFAULT )
/* Generated */        optInLipsOffset = 3;
/* Generated */     else if( ((int)optInLipsOffset < 1) || ((int)optInLipsOffset > 100000) )
/* Generated */        return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */     if( optInJawPeriod <= optInTeethPeriod )
/* Generated */        return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */     if( optInTeethPeriod <= optInLipsPeriod )
/* Generated */        return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */     if( (optInJawPeriod + optInJawOffset) <= (optInTeethPeriod + optInTeethOffset) )
/* Generated */        return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */     if( (optInTeethPeriod + optInTeethOffset) <= (optInLipsPeriod + optInLipsOffset) )
/* Generated */        return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */     #if !defined(_JAVA)
/* Generated */     if( !outJaw || !outTeeth || !outLips )
/* Generated */        return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */     #endif
/* Generated */  #endif
/* Generated */  #endif 
/* Generated */    jawSpan   = optInJawPeriod   + optInJawOffset   - 1;
/* Generated */    teethSpan = optInTeethPeriod + optInTeethOffset - 1;
/* Generated */    lipsSpan  = optInLipsPeriod  + optInLipsOffset  - 1;
/* Generated */    lookbackTotal = jawSpan;
/* Generated */    if( teethSpan > lookbackTotal )
/* Generated */       lookbackTotal = teethSpan;
/* Generated */    if( lipsSpan > lookbackTotal )
/* Generated */       lookbackTotal = lipsSpan;
/* Generated */    firstCalcIdx = jawSpan;
/* Generated */    if( teethSpan < firstCalcIdx )
/* Generated */       firstCalcIdx = teethSpan;
/* Generated */    if( lipsSpan < firstCalcIdx )
/* Generated */       firstCalcIdx = lipsSpan;
/* Generated */    if( startIdx < lookbackTotal )
/* Generated */       startIdx = lookbackTotal;
/* Generated */    if( startIdx > endIdx )
/* Generated */    {
/* Generated */       VALUE_HANDLE_DEREF_TO_ZERO(outBegIdx);
/* Generated */       VALUE_HANDLE_DEREF_TO_ZERO(outNBElement);
/* Generated */       return ENUM_VALUE(RetCode,TA_SUCCESS,Success);
/* Generated */    }
/* Generated */    if( firstCalcIdx < startIdx )
/* Generated */    {
/* Generated */       for( today = firstCalcIdx; today < startIdx; ++today )
/* Generated */       {
/* Generated */          double tmpJaw   = TA_REAL_DEFAULT;
/* Generated */          double tmpTeeth = TA_REAL_DEFAULT;
/* Generated */          double tmpLips  = TA_REAL_DEFAULT;
/* Generated */ #define CALC_LINE(periodVar, offsetVar, startVar, initVar, prevVar, valueVar) \
/* Generated */          do { \
/* Generated */             if( today >= (startVar) ) \
/* Generated */             { \
/* Generated */                if( !(initVar) ) \
/* Generated */                { \
/* Generated */                   double sum_ = 0.0; \
/* Generated */                   int idx_; \
/* Generated */                   int begin_ = today - (offsetVar) - (periodVar) + 1; \
/* Generated */                   int end_ = today - (offsetVar); \
/* Generated */                   for( idx_ = begin_; idx_ <= end_; ++idx_ ) \
/* Generated */                      sum_ += (((double)inHigh[idx_]) + ((double)inLow[idx_])) * 0.5; \
/* Generated */                   valueVar = sum_ / (double)(periodVar); \
/* Generated */                   initVar = 1; \
/* Generated */                } \
/* Generated */                else \
/* Generated */                { \
/* Generated */                   double input_ = (((double)inHigh[today - (offsetVar)]) + ((double)inLow[today - (offsetVar)])) * 0.5; \
/* Generated */                   valueVar = ((prevVar * ((double)(periodVar) - 1.0)) + input_) / (double)(periodVar); \
/* Generated */                } \
/* Generated */                prevVar = valueVar; \
/* Generated */             } \
/* Generated */          } while(0)
/* Generated */          CALC_LINE(optInJawPeriod, optInJawOffset, jawSpan, jawInitialized, jawPrev, tmpJaw);
/* Generated */          CALC_LINE(optInTeethPeriod, optInTeethOffset, teethSpan, teethInitialized, teethPrev, tmpTeeth);
/* Generated */          CALC_LINE(optInLipsPeriod, optInLipsOffset, lipsSpan, lipsInitialized, lipsPrev, tmpLips);
/* Generated */ #undef CALC_LINE
/* Generated */       }
/* Generated */    }
/* Generated */    outIdx = 0;
/* Generated */    for( today = startIdx; today <= endIdx; ++today )
/* Generated */    {
/* Generated */    double jawValue   = TA_REAL_DEFAULT;
/* Generated */    double teethValue = TA_REAL_DEFAULT;
/* Generated */    double lipsValue  = TA_REAL_DEFAULT;
/* Generated */ #define CALC_LINE(periodVar, offsetVar, startVar, initVar, prevVar, valueVar) \
/* Generated */       do { \
/* Generated */          if( today >= (startVar) ) \
/* Generated */          { \
/* Generated */             if( !(initVar) ) \
/* Generated */             { \
/* Generated */                double sum_ = 0.0; \
/* Generated */                int idx_; \
/* Generated */                int begin_ = today - (offsetVar) - (periodVar) + 1; \
/* Generated */                int end_ = today - (offsetVar); \
/* Generated */                for( idx_ = begin_; idx_ <= end_; ++idx_ ) \
/* Generated */                   sum_ += (((double)inHigh[idx_]) + ((double)inLow[idx_])) * 0.5; \
/* Generated */                valueVar = sum_ / (double)(periodVar); \
/* Generated */                initVar = 1; \
/* Generated */             } \
/* Generated */             else \
/* Generated */             { \
/* Generated */                double input_ = (((double)inHigh[today - (offsetVar)]) + ((double)inLow[today - (offsetVar)])) * 0.5; \
/* Generated */                valueVar = ((prevVar * ((double)(periodVar) - 1.0)) + input_) / (double)(periodVar); \
/* Generated */             } \
/* Generated */             prevVar = valueVar; \
/* Generated */          } \
/* Generated */          else \
/* Generated */          { \
/* Generated */             valueVar = TA_REAL_DEFAULT; \
/* Generated */          } \
/* Generated */       } while(0)
/* Generated */       CALC_LINE(optInJawPeriod, optInJawOffset, jawSpan, jawInitialized, jawPrev, jawValue);
/* Generated */       CALC_LINE(optInTeethPeriod, optInTeethOffset, teethSpan, teethInitialized, teethPrev, teethValue);
/* Generated */       CALC_LINE(optInLipsPeriod, optInLipsOffset, lipsSpan, lipsInitialized, lipsPrev, lipsValue);
/* Generated */ #undef CALC_LINE
/* Generated */       outJaw[outIdx]   = jawValue;
/* Generated */       outTeeth[outIdx] = teethValue;
/* Generated */       outLips[outIdx]  = lipsValue;
/* Generated */       outIdx++;
/* Generated */    }
/* Generated */    VALUE_HANDLE_DEREF(outBegIdx)    = startIdx;
/* Generated */    VALUE_HANDLE_DEREF(outNBElement) = outIdx;
/* Generated */    return ENUM_VALUE(RetCode,TA_SUCCESS,Success);
/* Generated */ }
/* Generated */ 
/* Generated */ #if defined( _MANAGED )
/* Generated */ }}} // Close namespace TicTacTec.TA.Lib
/* Generated */ #elif defined( _RUST )
/* Generated */ } // Close impl core
/* Generated */ #endif
/**** END GENCODE SECTION 5 - DO NOT DELETE THIS LINE ****/
